# Generated by Django 4.2.6 on 2023-10-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description_short', models.CharField(max_length=200, verbose_name='Краткоен описание')),
                ('description_long', models.TextField(verbose_name='Описание')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
            ],
        ),
    ]
